blank_issues_enabled: true
contact_links:
  - name: Thunderstore page
    url: https://thunderstore.io/c/peak/p/llucasandersen/The_All_You_Need_Save_Manager/
    about: View release notes and install info on Thunderstore.
